/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package screen;

import collector.DbManager;
import collector.IDbManager;
import indexador.Document;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import processador.Processador;

/**
 *
 * @author Marc
 */
public class Screen2 extends javax.swing.JFrame {

    /**
     * Creates new form Screen2
     */
    public Screen2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        tab1 = new javax.swing.JPanel();
        tab1Search = new javax.swing.JPanel();
        tab1SearchLabel = new javax.swing.JLabel();
        tab1SearchText = new javax.swing.JTextField();
        tab1SearchButton = new javax.swing.JButton();
        tab1Options = new javax.swing.JPanel();
        tab1OptionsNbdocsLabel = new javax.swing.JLabel();
        tab1OptionsNbdocsText = new javax.swing.JTextField();
        tab1Content = new javax.swing.JScrollPane();
        tab1ContentList = new javax.swing.JList();
        tab1Title = new javax.swing.JLabel();
        tab2 = new javax.swing.JPanel();
        tab2Title = new javax.swing.JPanel();
        tab2TitleText = new javax.swing.JLabel();
        tab2Launch = new javax.swing.JPanel();
        tab2LaunchLabel = new javax.swing.JLabel();
        tab2LaunchButton = new javax.swing.JButton();
        tab2Status = new javax.swing.JPanel();
        tab2StatusLabel = new javax.swing.JLabel();
        tab2StatusFreqLabel = new javax.swing.JLabel();
        tab2StatusFreqText = new javax.swing.JLabel();
        tab2StatusTFLabel = new javax.swing.JLabel();
        tab2StatusTFText = new javax.swing.JLabel();
        tab2StatusIDFLabel = new javax.swing.JLabel();
        tab2StatusIDFText = new javax.swing.JLabel();
        tab2StatusWLabel = new javax.swing.JLabel();
        tab2StatusWText = new javax.swing.JLabel();
        tab2StatusRLabel = new javax.swing.JLabel();
        tab2StatusRText = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        tab3 = new javax.swing.JPanel();
        tab3Title = new javax.swing.JPanel();
        tab3TitleText = new javax.swing.JLabel();
        tab2Launch1 = new javax.swing.JPanel();
        tab2LaunchLabel1 = new javax.swing.JLabel();
        tab2LaunchButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        tab1SearchLabel.setText("Busca");

        tab1SearchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tab1SearchTextActionPerformed(evt);
            }
        });

        tab1SearchButton.setText("Buscar");
        tab1SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tab1SearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tab1SearchLayout = new javax.swing.GroupLayout(tab1Search);
        tab1Search.setLayout(tab1SearchLayout);
        tab1SearchLayout.setHorizontalGroup(
            tab1SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1SearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab1SearchLabel)
                .addGap(18, 18, 18)
                .addComponent(tab1SearchText)
                .addGap(18, 18, 18)
                .addComponent(tab1SearchButton)
                .addGap(2, 2, 2))
        );
        tab1SearchLayout.setVerticalGroup(
            tab1SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tab1SearchLabel)
                .addComponent(tab1SearchText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(tab1SearchButton))
        );

        tab1OptionsNbdocsLabel.setText("Número de resultados");

        tab1OptionsNbdocsText.setText("5");
        tab1OptionsNbdocsText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tab1OptionsNbdocsTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tab1OptionsLayout = new javax.swing.GroupLayout(tab1Options);
        tab1Options.setLayout(tab1OptionsLayout);
        tab1OptionsLayout.setHorizontalGroup(
            tab1OptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1OptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab1OptionsNbdocsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tab1OptionsNbdocsText, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab1OptionsLayout.setVerticalGroup(
            tab1OptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1OptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tab1OptionsNbdocsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(tab1OptionsNbdocsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tab1ContentList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tab1Content.setViewportView(tab1ContentList);

        tab1Title.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        tab1Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tab1Title.setText("Processador");

        javax.swing.GroupLayout tab1Layout = new javax.swing.GroupLayout(tab1);
        tab1.setLayout(tab1Layout);
        tab1Layout.setHorizontalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tab1Options, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tab1Content)
                    .addComponent(tab1Search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tab1Layout.createSequentialGroup()
                        .addComponent(tab1Title, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tab1Layout.setVerticalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab1Title, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tab1Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tab1Options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tab1Content, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Processador", tab1);

        tab2TitleText.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        tab2TitleText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tab2TitleText.setText("Indexador");

        javax.swing.GroupLayout tab2TitleLayout = new javax.swing.GroupLayout(tab2Title);
        tab2Title.setLayout(tab2TitleLayout);
        tab2TitleLayout.setHorizontalGroup(
            tab2TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab2TitleText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        tab2TitleLayout.setVerticalGroup(
            tab2TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab2TitleText, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        tab2LaunchLabel.setText("Iniciar o indexador");

        tab2LaunchButton.setText("GO !");
        tab2LaunchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tab2LaunchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tab2LaunchLayout = new javax.swing.GroupLayout(tab2Launch);
        tab2Launch.setLayout(tab2LaunchLayout);
        tab2LaunchLayout.setHorizontalGroup(
            tab2LaunchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2LaunchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab2LaunchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(tab2LaunchButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab2LaunchLayout.setVerticalGroup(
            tab2LaunchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab2LaunchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab2LaunchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        tab2StatusLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tab2StatusLabel.setText("Estado");
        tab2StatusLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tab2StatusFreqLabel.setText("Frequências :");

        tab2StatusFreqText.setText("...");

        tab2StatusTFLabel.setText("Calculo do TF :");

        tab2StatusTFText.setText("...");

        tab2StatusIDFLabel.setText("Calculo do IDF :");

        tab2StatusIDFText.setText("...");

        tab2StatusWLabel.setText("Calculo do peso :");

        tab2StatusWText.setText("...");

        tab2StatusRLabel.setText("Calculo do R :");

        tab2StatusRText.setText("...");

        javax.swing.GroupLayout tab2StatusLayout = new javax.swing.GroupLayout(tab2Status);
        tab2Status.setLayout(tab2StatusLayout);
        tab2StatusLayout.setHorizontalGroup(
            tab2StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2StatusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab2StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tab2StatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tab2StatusLayout.createSequentialGroup()
                        .addComponent(tab2StatusRLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tab2StatusRText, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                    .addGroup(tab2StatusLayout.createSequentialGroup()
                        .addComponent(tab2StatusTFLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tab2StatusTFText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(tab2StatusLayout.createSequentialGroup()
                        .addComponent(tab2StatusFreqLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tab2StatusFreqText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(tab2StatusLayout.createSequentialGroup()
                        .addComponent(tab2StatusIDFLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tab2StatusIDFText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(tab2StatusLayout.createSequentialGroup()
                        .addComponent(tab2StatusWLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tab2StatusWText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tab2StatusLayout.setVerticalGroup(
            tab2StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2StatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab2StatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(tab2StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tab2StatusFreqLabel)
                    .addComponent(tab2StatusFreqText))
                .addGap(18, 18, 18)
                .addGroup(tab2StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tab2StatusTFLabel)
                    .addComponent(tab2StatusTFText))
                .addGap(18, 18, 18)
                .addGroup(tab2StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tab2StatusIDFLabel)
                    .addComponent(tab2StatusIDFText))
                .addGap(18, 18, 18)
                .addGroup(tab2StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tab2StatusWLabel)
                    .addComponent(tab2StatusWText))
                .addGap(18, 18, 18)
                .addGroup(tab2StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tab2StatusRLabel)
                    .addComponent(tab2StatusRText))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Vocabulário");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout tab2Layout = new javax.swing.GroupLayout(tab2);
        tab2.setLayout(tab2Layout);
        tab2Layout.setHorizontalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tab2Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tab2Launch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tab2Layout.createSequentialGroup()
                        .addComponent(tab2Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tab2Layout.setVerticalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab2Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tab2Launch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tab2Status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Indexador", tab2);

        tab3TitleText.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        tab3TitleText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tab3TitleText.setText("Coletor");

        javax.swing.GroupLayout tab3TitleLayout = new javax.swing.GroupLayout(tab3Title);
        tab3Title.setLayout(tab3TitleLayout);
        tab3TitleLayout.setHorizontalGroup(
            tab3TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab3TitleText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        tab3TitleLayout.setVerticalGroup(
            tab3TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab3TitleText, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        tab2LaunchLabel1.setText("Iniciar o Coletor");

        tab2LaunchButton1.setText("GO !");
        tab2LaunchButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tab2LaunchButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tab2Launch1Layout = new javax.swing.GroupLayout(tab2Launch1);
        tab2Launch1.setLayout(tab2Launch1Layout);
        tab2Launch1Layout.setHorizontalGroup(
            tab2Launch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Launch1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab2LaunchLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(tab2LaunchButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab2Launch1Layout.setVerticalGroup(
            tab2Launch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Launch1Layout.createSequentialGroup()
                .addGroup(tab2Launch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tab2LaunchLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tab2LaunchButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Documentos");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jScrollPane2.setViewportView(jList2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout tab3Layout = new javax.swing.GroupLayout(tab3);
        tab3.setLayout(tab3Layout);
        tab3Layout.setHorizontalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tab3Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tab2Launch1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        tab3Layout.setVerticalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab3Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tab2Launch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        jTabbedPane1.addTab("Coletor", tab3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tab1SearchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tab1SearchTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tab1SearchTextActionPerformed

    private void tab1SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tab1SearchButtonActionPerformed
        LinkedList<Document> docs = new LinkedList<Document>();
        
        String query = tab1SearchText.getText();
        int nb_docs;
        
        try
        {
            nb_docs = Integer.parseInt(tab1OptionsNbdocsText.getText());
            if (nb_docs <= 0)
                throw new Exception();
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,"Wrong Documents Number");
            return;
        }
        

        Processador proc = new Processador(query);
        try 
        {
            docs = proc.run(nb_docs);
        } 
        catch (SQLException ex) { Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex); }
//        JLabel jLabel2 = new JLabel();
//        jLabel2.setText("jLabel2");
//        JLabel jLabel3 = new JLabel();
//        jLabel3.setText("jPanel3");
        //jScrollPane1.setViewportView(jLabel2);
//        tab1Content.getViewport().add(jLabel2);
//        tab1Content.getViewport().add(jLabel3);
//        jList1.removeAll();
//        tab1Content.setViewportView(jList1);
        
        if (docs.size() > 0)
        {
            DefaultListModel listModel = new DefaultListModel();
            for (Document doc : docs)
            {
                String listElem = "";
                listElem += doc.getName();
                listElem += " - " + doc.getUrl();
                listModel.addElement(listElem);
            }
            tab1ContentList.setModel(listModel);
            this.repaint();
            this.validate();
            this.pack();
        }

    }//GEN-LAST:event_tab1SearchButtonActionPerformed

    private void tab1OptionsNbdocsTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tab1OptionsNbdocsTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tab1OptionsNbdocsTextActionPerformed

    private void tab2LaunchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tab2LaunchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tab2LaunchButtonActionPerformed

    private void tab2LaunchButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tab2LaunchButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tab2LaunchButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IDbManager d = DbManager.getInstance();
                d.setUrl("jdbc:mysql://localhost:3306/topicos_sri");
                d.connect();
                new Screen2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel tab1;
    private javax.swing.JScrollPane tab1Content;
    private javax.swing.JList tab1ContentList;
    private javax.swing.JPanel tab1Options;
    private javax.swing.JLabel tab1OptionsNbdocsLabel;
    private javax.swing.JTextField tab1OptionsNbdocsText;
    private javax.swing.JPanel tab1Search;
    private javax.swing.JButton tab1SearchButton;
    private javax.swing.JLabel tab1SearchLabel;
    private javax.swing.JTextField tab1SearchText;
    private javax.swing.JLabel tab1Title;
    private javax.swing.JPanel tab2;
    private javax.swing.JPanel tab2Launch;
    private javax.swing.JPanel tab2Launch1;
    private javax.swing.JButton tab2LaunchButton;
    private javax.swing.JButton tab2LaunchButton1;
    private javax.swing.JLabel tab2LaunchLabel;
    private javax.swing.JLabel tab2LaunchLabel1;
    private javax.swing.JPanel tab2Status;
    private javax.swing.JLabel tab2StatusFreqLabel;
    private javax.swing.JLabel tab2StatusFreqText;
    private javax.swing.JLabel tab2StatusIDFLabel;
    private javax.swing.JLabel tab2StatusIDFText;
    private javax.swing.JLabel tab2StatusLabel;
    private javax.swing.JLabel tab2StatusRLabel;
    private javax.swing.JLabel tab2StatusRText;
    private javax.swing.JLabel tab2StatusTFLabel;
    private javax.swing.JLabel tab2StatusTFText;
    private javax.swing.JLabel tab2StatusWLabel;
    private javax.swing.JLabel tab2StatusWText;
    private javax.swing.JPanel tab2Title;
    private javax.swing.JLabel tab2TitleText;
    private javax.swing.JPanel tab3;
    private javax.swing.JPanel tab3Title;
    private javax.swing.JLabel tab3TitleText;
    // End of variables declaration//GEN-END:variables
}
