/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package screen;

import collector.Collector;
import collector.DbManager;
import collector.IDbManager;
import indexador.Document;
import indexador.Indexador;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.List;
import java.util.Queue;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import processador.Processador;

/**
 *
 * @author Marc
 */
public class Screen extends javax.swing.JFrame implements MyListener {

    private     LinkedList<String> urls = new LinkedList<String>();
    
    
    /**
     * Creates new form Screen2
     */
    public Screen() {
        initComponents();
        
        urls.add("http://www.kram47.fr");
        //urls.add("http://www.stf.jus.br/portal/principal/principal.asp");
        //urls.add("http://www.camara.gov.br");
        //urls.add("http://www.senado.gov.br/");
        DefaultListModel listModel = new DefaultListModel();
        for (String url : urls)
            listModel.addElement(url);
        tab3SitesList.setModel(listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        tab1 = new javax.swing.JPanel();
        tab1Search = new javax.swing.JPanel();
        tab1SearchLabel = new javax.swing.JLabel();
        tab1SearchText = new javax.swing.JTextField();
        tab1SearchButton = new javax.swing.JButton();
        tab1Options = new javax.swing.JPanel();
        tab1OptionsNbdocsLabel = new javax.swing.JLabel();
        tab1OptionsNbdocsText = new javax.swing.JTextField();
        tab1Content = new javax.swing.JScrollPane();
        tab1ContentList = new javax.swing.JList();
        tab1Title = new javax.swing.JLabel();
        tab2 = new javax.swing.JPanel();
        tab2Title = new javax.swing.JPanel();
        tab2TitleText = new javax.swing.JLabel();
        tab2Launch = new javax.swing.JPanel();
        tab2LaunchLabel = new javax.swing.JLabel();
        tab2LaunchGoButton = new javax.swing.JButton();
        tab2Status = new javax.swing.JPanel();
        tab2StatusLabel = new javax.swing.JLabel();
        tab2StatusFreqLabel = new javax.swing.JLabel();
        tab2StatusFreqText = new javax.swing.JLabel();
        tab2StatusTFLabel = new javax.swing.JLabel();
        tab2StatusTFText = new javax.swing.JLabel();
        tab2StatusIDFLabel = new javax.swing.JLabel();
        tab2StatusIDFText = new javax.swing.JLabel();
        tab2StatusWLabel = new javax.swing.JLabel();
        tab2StatusWText = new javax.swing.JLabel();
        tab2StatusRLabel = new javax.swing.JLabel();
        tab2StatusRText = new javax.swing.JLabel();
        tab2Vocabulary = new javax.swing.JPanel();
        tab2VocabularyLabel = new javax.swing.JLabel();
        tab2VocabularyScroll = new javax.swing.JScrollPane();
        tab2VocabularyList = new javax.swing.JList();
        tab2VocabularyRefreshButton = new javax.swing.JButton();
        tab3 = new javax.swing.JPanel();
        tab3Title = new javax.swing.JPanel();
        tab3TitleText = new javax.swing.JLabel();
        tab3Launch = new javax.swing.JPanel();
        tab3LaunchLabel = new javax.swing.JLabel();
        tab3LaunchGOButton = new javax.swing.JButton();
        tab3Sites = new javax.swing.JPanel();
        tab3SitesLabel = new javax.swing.JLabel();
        tab3SitesAddText = new javax.swing.JTextField();
        tab3SitesAddButon = new javax.swing.JButton();
        tab3SitesDeleteButton = new javax.swing.JButton();
        tab3SitesScroll = new javax.swing.JScrollPane();
        tab3SitesList = new javax.swing.JList();
        tab3Documents = new javax.swing.JPanel();
        tab3DocumentsLabel = new javax.swing.JLabel();
        tab3DocumentsRefreshButton = new javax.swing.JButton();
        tab3DocumentsScroll = new javax.swing.JScrollPane();
        tab3DocumentsList = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        tab1SearchLabel.setText("Busca");

        tab1SearchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tab1SearchTextActionPerformed(evt);
            }
        });

        tab1SearchButton.setText("Buscar");
        tab1SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tab1SearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tab1SearchLayout = new javax.swing.GroupLayout(tab1Search);
        tab1Search.setLayout(tab1SearchLayout);
        tab1SearchLayout.setHorizontalGroup(
            tab1SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1SearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab1SearchLabel)
                .addGap(18, 18, 18)
                .addComponent(tab1SearchText)
                .addGap(18, 18, 18)
                .addComponent(tab1SearchButton)
                .addGap(2, 2, 2))
        );
        tab1SearchLayout.setVerticalGroup(
            tab1SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tab1SearchLabel)
                .addComponent(tab1SearchText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(tab1SearchButton))
        );

        tab1OptionsNbdocsLabel.setText("Número de resultados");

        tab1OptionsNbdocsText.setText("5");
        tab1OptionsNbdocsText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tab1OptionsNbdocsTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tab1OptionsLayout = new javax.swing.GroupLayout(tab1Options);
        tab1Options.setLayout(tab1OptionsLayout);
        tab1OptionsLayout.setHorizontalGroup(
            tab1OptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1OptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab1OptionsNbdocsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tab1OptionsNbdocsText, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab1OptionsLayout.setVerticalGroup(
            tab1OptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1OptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tab1OptionsNbdocsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(tab1OptionsNbdocsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tab1ContentList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tab1Content.setViewportView(tab1ContentList);

        tab1Title.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        tab1Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tab1Title.setText("Processador");

        javax.swing.GroupLayout tab1Layout = new javax.swing.GroupLayout(tab1);
        tab1.setLayout(tab1Layout);
        tab1Layout.setHorizontalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tab1Options, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tab1Content)
                    .addComponent(tab1Search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tab1Layout.createSequentialGroup()
                        .addComponent(tab1Title, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 78, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tab1Layout.setVerticalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab1Title, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tab1Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tab1Options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tab1Content, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Processador", tab1);

        tab2TitleText.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        tab2TitleText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tab2TitleText.setText("Indexador");

        javax.swing.GroupLayout tab2TitleLayout = new javax.swing.GroupLayout(tab2Title);
        tab2Title.setLayout(tab2TitleLayout);
        tab2TitleLayout.setHorizontalGroup(
            tab2TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab2TitleText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        tab2TitleLayout.setVerticalGroup(
            tab2TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab2TitleText, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        tab2LaunchLabel.setText("Iniciar o indexador");

        tab2LaunchGoButton.setText("GO !");
        tab2LaunchGoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tab2LaunchGoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tab2LaunchLayout = new javax.swing.GroupLayout(tab2Launch);
        tab2Launch.setLayout(tab2LaunchLayout);
        tab2LaunchLayout.setHorizontalGroup(
            tab2LaunchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2LaunchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab2LaunchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tab2LaunchGoButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab2LaunchLayout.setVerticalGroup(
            tab2LaunchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2LaunchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tab2LaunchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(tab2LaunchGoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab2Status.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tab2StatusLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tab2StatusLabel.setText("Estado");
        tab2StatusLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tab2StatusFreqLabel.setText("Frequências :");

        tab2StatusFreqText.setText("...");

        tab2StatusTFLabel.setText("Calculo do TF :");

        tab2StatusTFText.setText("...");

        tab2StatusIDFLabel.setText("Calculo do IDF :");

        tab2StatusIDFText.setText("...");

        tab2StatusWLabel.setText("Calculo do peso :");

        tab2StatusWText.setText("...");

        tab2StatusRLabel.setText("Calculo do R :");

        tab2StatusRText.setText("...");

        javax.swing.GroupLayout tab2StatusLayout = new javax.swing.GroupLayout(tab2Status);
        tab2Status.setLayout(tab2StatusLayout);
        tab2StatusLayout.setHorizontalGroup(
            tab2StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2StatusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab2StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab2StatusLayout.createSequentialGroup()
                        .addComponent(tab2StatusRLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tab2StatusRText, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                    .addGroup(tab2StatusLayout.createSequentialGroup()
                        .addComponent(tab2StatusTFLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tab2StatusTFText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(tab2StatusLayout.createSequentialGroup()
                        .addComponent(tab2StatusFreqLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tab2StatusFreqText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(tab2StatusLayout.createSequentialGroup()
                        .addComponent(tab2StatusIDFLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tab2StatusIDFText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(tab2StatusLayout.createSequentialGroup()
                        .addComponent(tab2StatusWLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tab2StatusWText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(tab2StatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        tab2StatusLayout.setVerticalGroup(
            tab2StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2StatusLayout.createSequentialGroup()
                .addComponent(tab2StatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(tab2StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tab2StatusFreqLabel)
                    .addComponent(tab2StatusFreqText))
                .addGap(18, 18, 18)
                .addGroup(tab2StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tab2StatusTFLabel)
                    .addComponent(tab2StatusTFText))
                .addGap(18, 18, 18)
                .addGroup(tab2StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tab2StatusIDFLabel)
                    .addComponent(tab2StatusIDFText))
                .addGap(18, 18, 18)
                .addGroup(tab2StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tab2StatusWLabel)
                    .addComponent(tab2StatusWText))
                .addGap(18, 18, 18)
                .addGroup(tab2StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tab2StatusRLabel)
                    .addComponent(tab2StatusRText))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        tab2VocabularyLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tab2VocabularyLabel.setText(" Vocabulário");
        tab2VocabularyLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tab2VocabularyScroll.setViewportView(tab2VocabularyList);

        tab2VocabularyRefreshButton.setText("Refrescar");
        tab2VocabularyRefreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tab2VocabularyRefreshButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tab2VocabularyLayout = new javax.swing.GroupLayout(tab2Vocabulary);
        tab2Vocabulary.setLayout(tab2VocabularyLayout);
        tab2VocabularyLayout.setHorizontalGroup(
            tab2VocabularyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2VocabularyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab2VocabularyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tab2VocabularyScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                    .addGroup(tab2VocabularyLayout.createSequentialGroup()
                        .addComponent(tab2VocabularyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tab2VocabularyRefreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tab2VocabularyLayout.setVerticalGroup(
            tab2VocabularyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab2VocabularyLayout.createSequentialGroup()
                .addGroup(tab2VocabularyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tab2VocabularyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tab2VocabularyRefreshButton))
                .addGap(31, 31, 31)
                .addComponent(tab2VocabularyScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout tab2Layout = new javax.swing.GroupLayout(tab2);
        tab2.setLayout(tab2Layout);
        tab2Layout.setHorizontalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tab2Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tab2Launch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tab2Layout.createSequentialGroup()
                        .addComponent(tab2Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tab2Vocabulary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tab2Layout.setVerticalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab2Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tab2Launch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tab2Vocabulary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tab2Layout.createSequentialGroup()
                        .addComponent(tab2Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Indexador", tab2);

        tab3TitleText.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        tab3TitleText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tab3TitleText.setText("Coletor");

        javax.swing.GroupLayout tab3TitleLayout = new javax.swing.GroupLayout(tab3Title);
        tab3Title.setLayout(tab3TitleLayout);
        tab3TitleLayout.setHorizontalGroup(
            tab3TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab3TitleText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        tab3TitleLayout.setVerticalGroup(
            tab3TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab3TitleText, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        tab3LaunchLabel.setText("Iniciar o Coletor");

        tab3LaunchGOButton.setText("GO !");
        tab3LaunchGOButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tab3LaunchGOButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tab3LaunchLayout = new javax.swing.GroupLayout(tab3Launch);
        tab3Launch.setLayout(tab3LaunchLayout);
        tab3LaunchLayout.setHorizontalGroup(
            tab3LaunchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab3LaunchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab3LaunchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addComponent(tab3LaunchGOButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab3LaunchLayout.setVerticalGroup(
            tab3LaunchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab3LaunchLayout.createSequentialGroup()
                .addGroup(tab3LaunchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tab3LaunchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tab3LaunchGOButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tab3SitesLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tab3SitesLabel.setText("Sites Web");
        tab3SitesLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tab3SitesAddText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tab3SitesAddTextActionPerformed(evt);
            }
        });

        tab3SitesAddButon.setText("Adicionar Site");
        tab3SitesAddButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tab3SitesAddButonActionPerformed(evt);
            }
        });

        tab3SitesDeleteButton.setText("Deletar Site Selecionado");
        tab3SitesDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tab3SitesDeleteButtonActionPerformed(evt);
            }
        });

        tab3SitesScroll.setViewportView(tab3SitesList);

        javax.swing.GroupLayout tab3SitesLayout = new javax.swing.GroupLayout(tab3Sites);
        tab3Sites.setLayout(tab3SitesLayout);
        tab3SitesLayout.setHorizontalGroup(
            tab3SitesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab3SitesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab3SitesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tab3SitesScroll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(tab3SitesLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tab3SitesAddText)
                    .addComponent(tab3SitesDeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addComponent(tab3SitesAddButon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        tab3SitesLayout.setVerticalGroup(
            tab3SitesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab3SitesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab3SitesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tab3SitesAddText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tab3SitesAddButon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(tab3SitesDeleteButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tab3SitesScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tab3DocumentsLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tab3DocumentsLabel.setText("Documentos");
        tab3DocumentsLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tab3DocumentsRefreshButton.setText("Refrescar");
        tab3DocumentsRefreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tab3DocumentsRefreshButtonActionPerformed(evt);
            }
        });

        tab3DocumentsScroll.setViewportView(tab3DocumentsList);

        javax.swing.GroupLayout tab3DocumentsLayout = new javax.swing.GroupLayout(tab3Documents);
        tab3Documents.setLayout(tab3DocumentsLayout);
        tab3DocumentsLayout.setHorizontalGroup(
            tab3DocumentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab3DocumentsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab3DocumentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tab3DocumentsScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                    .addGroup(tab3DocumentsLayout.createSequentialGroup()
                        .addComponent(tab3DocumentsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(tab3DocumentsRefreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)))
                .addContainerGap())
        );
        tab3DocumentsLayout.setVerticalGroup(
            tab3DocumentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab3DocumentsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab3DocumentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tab3DocumentsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tab3DocumentsRefreshButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tab3DocumentsScroll)
                .addContainerGap())
        );

        javax.swing.GroupLayout tab3Layout = new javax.swing.GroupLayout(tab3);
        tab3.setLayout(tab3Layout);
        tab3Layout.setHorizontalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tab3Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tab3Launch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab3Layout.createSequentialGroup()
                        .addComponent(tab3Sites, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tab3Documents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tab3Layout.setVerticalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab3Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tab3Launch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tab3Documents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tab3Sites, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Coletor", tab3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tab1SearchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tab1SearchTextActionPerformed
        launchProcessador();
    }//GEN-LAST:event_tab1SearchTextActionPerformed

    private void tab1SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tab1SearchButtonActionPerformed
        launchProcessador();
    }//GEN-LAST:event_tab1SearchButtonActionPerformed

    private void launchProcessador()
    {
        LinkedList<Document> docs = new LinkedList<Document>();
        
        String query = tab1SearchText.getText();
        int nb_docs;
        
        try
        {
            nb_docs = Integer.parseInt(tab1OptionsNbdocsText.getText());
            if (nb_docs <= 0)
                throw new Exception();
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,"Wrong Documents Number");
            return;
        }
        

        Processador proc = new Processador(query);
        try 
        {
            docs = proc.run(nb_docs);
        } 
        catch (SQLException ex) { Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex); }
        
        if (docs.size() > 0)
        {
            DefaultListModel listModel = new DefaultListModel();
            for (Document doc : docs)
            {
                String listElem = "";
                listElem += doc.getTitle();
                listElem += "  - " + doc.getUrl();
                listModel.addElement(listElem);
            }
            tab1ContentList.setModel(listModel);

        }
    }
    
    private void tab1OptionsNbdocsTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tab1OptionsNbdocsTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tab1OptionsNbdocsTextActionPerformed

    private void tab3LaunchGOButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tab3LaunchGOButtonActionPerformed
        Collector myColector  = new Collector();
        myColector.setUrls(urls);
        myColector.run();
        try {
            refreshDocuments();
        } catch (SQLException ex) {
            Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tab3LaunchGOButtonActionPerformed

    private void tab2LaunchGoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tab2LaunchGoButtonActionPerformed
        Indexador indexador = new Indexador();
        try {
            
            indexador.setListener(this);
            indexador.run();
            
            refreshVocabulary();
        } catch (SQLException ex) {
            Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_tab2LaunchGoButtonActionPerformed

    private void refreshVocabulary() throws SQLException
    {
        LinkedList<String> words = Indexador.getVocabularyList();
            
        DefaultListModel listModel = new DefaultListModel();
        for (String word : words)
        {
            listModel.addElement(word);
        }
        tab2VocabularyList.setModel(listModel);
    }
    
    private void refreshDocuments() throws SQLException
    {
        LinkedList<String> docs = Indexador.getDocumentsList();
            
        DefaultListModel listModel = new DefaultListModel();
        for (String doc : docs)
        {
            listModel.addElement(doc);
        }
        tab3DocumentsList.setModel(listModel);
    }
    
    private void tab3SitesAddTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tab3SitesAddTextActionPerformed
        addUrl();
    }//GEN-LAST:event_tab3SitesAddTextActionPerformed

    private void tab3SitesDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tab3SitesDeleteButtonActionPerformed
        List<String> selected_urls = tab3SitesList.getSelectedValuesList();
        
        for (String url : selected_urls)
        {
            urls.remove(url);
        }
        
        DefaultListModel listModel = new DefaultListModel();
        for (String url : urls)
            listModel.addElement(url);
        tab3SitesList.setModel(listModel);
    }//GEN-LAST:event_tab3SitesDeleteButtonActionPerformed

    private void tab3SitesAddButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tab3SitesAddButonActionPerformed
        addUrl();
    }//GEN-LAST:event_tab3SitesAddButonActionPerformed

    private void tab2VocabularyRefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tab2VocabularyRefreshButtonActionPerformed
        try {
            refreshVocabulary();
        } catch (SQLException ex) {
            Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tab2VocabularyRefreshButtonActionPerformed

    private void tab3DocumentsRefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tab3DocumentsRefreshButtonActionPerformed
        try {
            refreshDocuments();
        } catch (SQLException ex) {
            Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tab3DocumentsRefreshButtonActionPerformed

    private void addUrl()
    {
        String new_url = tab3SitesAddText.getText();
        
        if (!new_url.isEmpty() && !urls.contains(new_url))
        {
            Pattern p=Pattern.compile("((http:\\/\\/|https:\\/\\/)?(www.)?(([a-zA-Z0-9-]){2,}\\.){1,4}([a-zA-Z]){2,6}(\\/([a-zA-Z-_\\/\\.0-9#:?=&;,]*)?)?)");
            Matcher m=p.matcher(new_url);
            if(m.find())
            {
                urls.add(new_url);
                DefaultListModel listModel = new DefaultListModel();
                for (String url : urls)
                    listModel.addElement(url);
                tab3SitesList.setModel(listModel);
                tab3SitesAddText.setText("");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "O site deve ser de uma forma correta !\n"
                        + "Exemplos : http://www.meusite.com, www.meusite.com, http://www.meusite.com/pagina.php, ... \n"
                        + "Regex : ((http:\\/\\/|https:\\/\\/)?(www.)?(([a-zA-Z0-9-]){2,}\\.){1,4}([a-zA-Z]){2,6}(\\/([a-zA-Z-_\\/\\.0-9#:?=&;,]*)?)?)");
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void run() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IDbManager d = DbManager.getInstance();
                new Screen().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel tab1;
    private javax.swing.JScrollPane tab1Content;
    private javax.swing.JList tab1ContentList;
    private javax.swing.JPanel tab1Options;
    private javax.swing.JLabel tab1OptionsNbdocsLabel;
    private javax.swing.JTextField tab1OptionsNbdocsText;
    private javax.swing.JPanel tab1Search;
    private javax.swing.JButton tab1SearchButton;
    private javax.swing.JLabel tab1SearchLabel;
    private javax.swing.JTextField tab1SearchText;
    private javax.swing.JLabel tab1Title;
    private javax.swing.JPanel tab2;
    private javax.swing.JPanel tab2Launch;
    private javax.swing.JButton tab2LaunchGoButton;
    private javax.swing.JLabel tab2LaunchLabel;
    private javax.swing.JPanel tab2Status;
    private javax.swing.JLabel tab2StatusFreqLabel;
    private javax.swing.JLabel tab2StatusFreqText;
    private javax.swing.JLabel tab2StatusIDFLabel;
    private javax.swing.JLabel tab2StatusIDFText;
    private javax.swing.JLabel tab2StatusLabel;
    private javax.swing.JLabel tab2StatusRLabel;
    private javax.swing.JLabel tab2StatusRText;
    private javax.swing.JLabel tab2StatusTFLabel;
    private javax.swing.JLabel tab2StatusTFText;
    private javax.swing.JLabel tab2StatusWLabel;
    private javax.swing.JLabel tab2StatusWText;
    private javax.swing.JPanel tab2Title;
    private javax.swing.JLabel tab2TitleText;
    private javax.swing.JPanel tab2Vocabulary;
    private javax.swing.JLabel tab2VocabularyLabel;
    private javax.swing.JList tab2VocabularyList;
    private javax.swing.JButton tab2VocabularyRefreshButton;
    private javax.swing.JScrollPane tab2VocabularyScroll;
    private javax.swing.JPanel tab3;
    private javax.swing.JPanel tab3Documents;
    private javax.swing.JLabel tab3DocumentsLabel;
    private javax.swing.JList tab3DocumentsList;
    private javax.swing.JButton tab3DocumentsRefreshButton;
    private javax.swing.JScrollPane tab3DocumentsScroll;
    private javax.swing.JPanel tab3Launch;
    private javax.swing.JButton tab3LaunchGOButton;
    private javax.swing.JLabel tab3LaunchLabel;
    private javax.swing.JPanel tab3Sites;
    private javax.swing.JButton tab3SitesAddButon;
    private javax.swing.JTextField tab3SitesAddText;
    private javax.swing.JButton tab3SitesDeleteButton;
    private javax.swing.JLabel tab3SitesLabel;
    private javax.swing.JList tab3SitesList;
    private javax.swing.JScrollPane tab3SitesScroll;
    private javax.swing.JPanel tab3Title;
    private javax.swing.JLabel tab3TitleText;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onCalculateFrequenciesFinish() {
        tab2StatusFreqText.setText("OK");
        System.out.println("Frequencies OK");
    }

    @Override
    public void onCalculateTFFinish() {
        tab2StatusTFText.setText("OK");
        System.out.println("TF OK");        
    }

    @Override
    public void onCalculateIDFFinish() {
        tab2StatusIDFText.setText("OK");
        System.out.println("IDF OK");        
    }

    @Override
    public void onCalculateWFinish() {
        tab2StatusWText.setText("OK");
        System.out.println("W OK");        
    }

    @Override
    public void onCalculateRFinish() {
        tab2StatusRText.setText("OK");
        System.out.println("R OK");        
    }
    
}
